jenkins:
  clouds:
  - docker:
      dockerApi:
        connectTimeout: 60
        dockerHost:
          uri: "${DOCKERCLOUDCONNECTION}"
        hostname: "${DOCKERHOSTNAME}"
        readTimeout: 60
      errorDuration: 60
      name: "docker_local"
      templates:
      - connector:
         ssh:
            launchTimeoutSeconds: 5
            maxNumRetries: 5
            retryWaitTime: 5
            sshKeyStrategy:
              manuallyConfiguredSSHKey:
                credentialsId: "ssh_jenkins"
                sshHostKeyVerificationStrategy: "nonVerifyingKeyVerificationStrategy"
        dockerTemplateBase:
          cpuPeriod: 100000
          cpuQuota: 100000
          image: "${arduinocli_image}"
          network: "${DOCKERNETWORK}"
          mounts:
          - "type=bind,source=${SSH_JENKINS_PUB_FILE},destination=/home/jenkins-slave/.ssh/authorized_keys"
          mountsString: "type=bind,source=${SSH_JENKINS_PUB_FILE},destination=/home/jenkins-slave/.ssh/authorized_keys"
          user: "jenkins-slave"
        instanceCapStr: "2"
        labelString: "arduinocli"
        mode: EXCLUSIVE
        name: "arduinocli"
        pullStrategy: PULL_NEVER
        pullTimeout: 300
        remoteFs: "/home/jenkins-slave/"
